// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nucleosomes.proto

package us.palpant.science.io;

public final class FrameProto {
  private FrameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FrameOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double time = 1;
    /**
     * <code>required double time = 1;</code>
     */
    boolean hasTime();
    /**
     * <code>required double time = 1;</code>
     */
    double getTime();

    // repeated uint32 positions = 2 [packed = true];
    /**
     * <code>repeated uint32 positions = 2 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getPositionsList();
    /**
     * <code>repeated uint32 positions = 2 [packed = true];</code>
     */
    int getPositionsCount();
    /**
     * <code>repeated uint32 positions = 2 [packed = true];</code>
     */
    int getPositions(int index);
  }
  /**
   * Protobuf type {@code Frame}
   */
  public static final class Frame extends
      com.google.protobuf.GeneratedMessage
      implements FrameOrBuilder {
    // Use Frame.newBuilder() to construct.
    private Frame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Frame(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Frame defaultInstance;
    public static Frame getDefaultInstance() {
      return defaultInstance;
    }

    public Frame getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Frame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              time_ = input.readDouble();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                positions_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              positions_.add(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                positions_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                positions_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          positions_ = java.util.Collections.unmodifiableList(positions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.palpant.science.io.FrameProto.internal_static_Frame_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.palpant.science.io.FrameProto.internal_static_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.palpant.science.io.FrameProto.Frame.class, us.palpant.science.io.FrameProto.Frame.Builder.class);
    }

    public static com.google.protobuf.Parser<Frame> PARSER =
        new com.google.protobuf.AbstractParser<Frame>() {
      public Frame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Frame(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Frame> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private double time_;
    /**
     * <code>required double time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double time = 1;</code>
     */
    public double getTime() {
      return time_;
    }

    // repeated uint32 positions = 2 [packed = true];
    public static final int POSITIONS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> positions_;
    /**
     * <code>repeated uint32 positions = 2 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getPositionsList() {
      return positions_;
    }
    /**
     * <code>repeated uint32 positions = 2 [packed = true];</code>
     */
    public int getPositionsCount() {
      return positions_.size();
    }
    /**
     * <code>repeated uint32 positions = 2 [packed = true];</code>
     */
    public int getPositions(int index) {
      return positions_.get(index);
    }
    private int positionsMemoizedSerializedSize = -1;

    private void initFields() {
      time_ = 0D;
      positions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, time_);
      }
      if (getPositionsList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(positionsMemoizedSerializedSize);
      }
      for (int i = 0; i < positions_.size(); i++) {
        output.writeUInt32NoTag(positions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, time_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < positions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(positions_.get(i));
        }
        size += dataSize;
        if (!getPositionsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        positionsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static us.palpant.science.io.FrameProto.Frame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.palpant.science.io.FrameProto.Frame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.palpant.science.io.FrameProto.Frame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.palpant.science.io.FrameProto.Frame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.palpant.science.io.FrameProto.Frame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static us.palpant.science.io.FrameProto.Frame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static us.palpant.science.io.FrameProto.Frame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static us.palpant.science.io.FrameProto.Frame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static us.palpant.science.io.FrameProto.Frame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static us.palpant.science.io.FrameProto.Frame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(us.palpant.science.io.FrameProto.Frame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Frame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements us.palpant.science.io.FrameProto.FrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return us.palpant.science.io.FrameProto.internal_static_Frame_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return us.palpant.science.io.FrameProto.internal_static_Frame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                us.palpant.science.io.FrameProto.Frame.class, us.palpant.science.io.FrameProto.Frame.Builder.class);
      }

      // Construct using us.palpant.science.FrameProto.Frame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        positions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return us.palpant.science.io.FrameProto.internal_static_Frame_descriptor;
      }

      public us.palpant.science.io.FrameProto.Frame getDefaultInstanceForType() {
        return us.palpant.science.io.FrameProto.Frame.getDefaultInstance();
      }

      public us.palpant.science.io.FrameProto.Frame build() {
        us.palpant.science.io.FrameProto.Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public us.palpant.science.io.FrameProto.Frame buildPartial() {
        us.palpant.science.io.FrameProto.Frame result = new us.palpant.science.io.FrameProto.Frame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          positions_ = java.util.Collections.unmodifiableList(positions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.positions_ = positions_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof us.palpant.science.io.FrameProto.Frame) {
          return mergeFrom((us.palpant.science.io.FrameProto.Frame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(us.palpant.science.io.FrameProto.Frame other) {
        if (other == us.palpant.science.io.FrameProto.Frame.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (!other.positions_.isEmpty()) {
          if (positions_.isEmpty()) {
            positions_ = other.positions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePositionsIsMutable();
            positions_.addAll(other.positions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        us.palpant.science.io.FrameProto.Frame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (us.palpant.science.io.FrameProto.Frame) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double time = 1;
      private double time_ ;
      /**
       * <code>required double time = 1;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double time = 1;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>required double time = 1;</code>
       */
      public Builder setTime(double value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0D;
        onChanged();
        return this;
      }

      // repeated uint32 positions = 2 [packed = true];
      private java.util.List<java.lang.Integer> positions_ = java.util.Collections.emptyList();
      private void ensurePositionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          positions_ = new java.util.ArrayList<java.lang.Integer>(positions_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint32 positions = 2 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getPositionsList() {
        return java.util.Collections.unmodifiableList(positions_);
      }
      /**
       * <code>repeated uint32 positions = 2 [packed = true];</code>
       */
      public int getPositionsCount() {
        return positions_.size();
      }
      /**
       * <code>repeated uint32 positions = 2 [packed = true];</code>
       */
      public int getPositions(int index) {
        return positions_.get(index);
      }
      /**
       * <code>repeated uint32 positions = 2 [packed = true];</code>
       */
      public Builder setPositions(
          int index, int value) {
        ensurePositionsIsMutable();
        positions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 positions = 2 [packed = true];</code>
       */
      public Builder addPositions(int value) {
        ensurePositionsIsMutable();
        positions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 positions = 2 [packed = true];</code>
       */
      public Builder addAllPositions(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePositionsIsMutable();
        super.addAll(values, positions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 positions = 2 [packed = true];</code>
       */
      public Builder clearPositions() {
        positions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Frame)
    }

    static {
      defaultInstance = new Frame(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Frame)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Frame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Frame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021nucleosomes.proto\",\n\005Frame\022\014\n\004time\030\001 \002" +
      "(\001\022\025\n\tpositions\030\002 \003(\rB\002\020\001B \n\022us.palpant." +
      "scienceB\nFrameProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Frame_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Frame_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Frame_descriptor,
              new java.lang.String[] { "Time", "Positions", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
